package com.db;
// default package
// Generated Nov 6, 2014 12:59:42 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admininfo generated by hbm2java
 */
@Entity
@Table(name = "admininfo", catalog = "cse545group4bank")
public class Admininfo implements java.io.Serializable {

	private String adminId;
	private String adminName;
	private String adminEmail;
	private String securityA1;
	private String securityA2;
	private String securityQ1;
	private String securityQ2;
	private String publicKey;

	public Admininfo() {
	}

	public Admininfo(String adminId, String adminName, String adminEmail,
			String securityA1, String securityA2, String securityQ1,
			String securityQ2) {
		this.adminId = adminId;
		this.adminName = adminName;
		this.adminEmail = adminEmail;
		this.securityA1 = securityA1;
		this.securityA2 = securityA2;
		this.securityQ1 = securityQ1;
		this.securityQ2 = securityQ2;
	}

	public Admininfo(String adminId, String adminName, String adminEmail,
			String securityA1, String securityA2, String securityQ1,
			String securityQ2, String publicKey) {
		this.adminId = adminId;
		this.adminName = adminName;
		this.adminEmail = adminEmail;
		this.securityA1 = securityA1;
		this.securityA2 = securityA2;
		this.securityQ1 = securityQ1;
		this.securityQ2 = securityQ2;
		this.publicKey = publicKey;
	}

	@Id
	@Column(name = "ADMIN_ID", unique = true, nullable = false, length = 40)
	public String getAdminId() {
		return this.adminId;
	}

	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	@Column(name = "ADMIN_NAME", nullable = false, length = 45)
	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	@Column(name = "ADMIN_EMAIL", nullable = false, length = 45)
	public String getAdminEmail() {
		return this.adminEmail;
	}

	public void setAdminEmail(String adminEmail) {
		this.adminEmail = adminEmail;
	}

	@Column(name = "SECURITY_A1", nullable = false, length = 45)
	public String getSecurityA1() {
		return this.securityA1;
	}

	public void setSecurityA1(String securityA1) {
		this.securityA1 = securityA1;
	}

	@Column(name = "SECURITY_A2", nullable = false, length = 45)
	public String getSecurityA2() {
		return this.securityA2;
	}

	public void setSecurityA2(String securityA2) {
		this.securityA2 = securityA2;
	}

	@Column(name = "SECURITY_Q1", nullable = false, length = 45)
	public String getSecurityQ1() {
		return this.securityQ1;
	}

	public void setSecurityQ1(String securityQ1) {
		this.securityQ1 = securityQ1;
	}

	@Column(name = "SECURITY_Q2", nullable = false, length = 45)
	public String getSecurityQ2() {
		return this.securityQ2;
	}

	public void setSecurityQ2(String securityQ2) {
		this.securityQ2 = securityQ2;
	}

	@Column(name = "PUBLIC_KEY", length = 90)
	public String getPublicKey() {
		return this.publicKey;
	}

	public void setPublicKey(String publicKey) {
		this.publicKey = publicKey;
	}

}
