package com.db;
// default package
// Generated Nov 6, 2014 12:59:42 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "cse545group4bank")
public class Employee implements java.io.Serializable {

	private String employeeId;
	private String employeeName;
	private String employeeUsername;
	private String employeeSalary;
	private String employeeDesignation;
	private Boolean employeeDeleteFlag;
	private String employeeEmailId;
	private String securityA1;
	private String securityA2;
	private Set<Transaction> transactions = new HashSet<Transaction>(0);
	private Set<AccountSummary> accountSummaries = new HashSet<AccountSummary>(
			0);
	private Set<Dummytransaction> dummytransactions = new HashSet<Dummytransaction>(
			0);

	public Employee() {
	}

	public Employee(String employeeId, String employeeName,
			String employeeUsername, String employeeEmailId, String securityA1,
			String securityA2) {
		this.employeeId = employeeId;
		this.employeeName = employeeName;
		this.employeeUsername = employeeUsername;
		this.employeeEmailId = employeeEmailId;
		this.securityA1 = securityA1;
		this.securityA2 = securityA2;
	}

	public Employee(String employeeId, String employeeName,
			String employeeUsername, String employeeSalary,
			String employeeDesignation, Boolean employeeDeleteFlag,
			String employeeEmailId, String securityA1, String securityA2,
			Set<Transaction> transactions,
			Set<AccountSummary> accountSummaries,
			Set<Dummytransaction> dummytransactions) {
		this.employeeId = employeeId;
		this.employeeName = employeeName;
		this.employeeUsername = employeeUsername;
		this.employeeSalary = employeeSalary;
		this.employeeDesignation = employeeDesignation;
		this.employeeDeleteFlag = employeeDeleteFlag;
		this.employeeEmailId = employeeEmailId;
		this.securityA1 = securityA1;
		this.securityA2 = securityA2;
		this.transactions = transactions;
		this.accountSummaries = accountSummaries;
		this.dummytransactions = dummytransactions;
	}

	@Id
	@Column(name = "EMPLOYEE_ID", unique = true, nullable = false, length = 40)
	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "EMPLOYEE_NAME", nullable = false, length = 45)
	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	@Column(name = "EMPLOYEE_USERNAME", nullable = false, length = 45)
	public String getEmployeeUsername() {
		return this.employeeUsername;
	}

	public void setEmployeeUsername(String employeeUsername) {
		this.employeeUsername = employeeUsername;
	}

	@Column(name = "EMPLOYEE_SALARY", length = 45)
	public String getEmployeeSalary() {
		return this.employeeSalary;
	}

	public void setEmployeeSalary(String employeeSalary) {
		this.employeeSalary = employeeSalary;
	}

	@Column(name = "EMPLOYEE_DESIGNATION", length = 45)
	public String getEmployeeDesignation() {
		return this.employeeDesignation;
	}

	public void setEmployeeDesignation(String employeeDesignation) {
		this.employeeDesignation = employeeDesignation;
	}

	@Column(name = "EMPLOYEE_DELETE_FLAG")
	public Boolean getEmployeeDeleteFlag() {
		return this.employeeDeleteFlag;
	}

	public void setEmployeeDeleteFlag(Boolean employeeDeleteFlag) {
		this.employeeDeleteFlag = employeeDeleteFlag;
	}

	@Column(name = "EMPLOYEE_EMAIL_ID", nullable = false, length = 45)
	public String getEmployeeEmailId() {
		return this.employeeEmailId;
	}

	public void setEmployeeEmailId(String employeeEmailId) {
		this.employeeEmailId = employeeEmailId;
	}

	@Column(name = "SECURITY_A1", nullable = false, length = 45)
	public String getSecurityA1() {
		return this.securityA1;
	}

	public void setSecurityA1(String securityA1) {
		this.securityA1 = securityA1;
	}

	@Column(name = "SECURITY_A2", nullable = false, length = 45)
	public String getSecurityA2() {
		return this.securityA2;
	}

	public void setSecurityA2(String securityA2) {
		this.securityA2 = securityA2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<Transaction> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<Transaction> transactions) {
		this.transactions = transactions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<AccountSummary> getAccountSummaries() {
		return this.accountSummaries;
	}

	public void setAccountSummaries(Set<AccountSummary> accountSummaries) {
		this.accountSummaries = accountSummaries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<Dummytransaction> getDummytransactions() {
		return this.dummytransactions;
	}

	public void setDummytransactions(Set<Dummytransaction> dummytransactions) {
		this.dummytransactions = dummytransactions;
	}

}
