package com.db;
// default package
// Generated Nov 6, 2014 12:59:42 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "transaction", catalog = "cse545group4bank")
public class Transaction implements java.io.Serializable {

	private int transactionId;
	private AccountSummary accountSummaryBySender;
	private Employee employee;
	private AccountSummary accountSummaryByReceiver;
	private int amount;
	private String time;
	private Boolean critical;
	private Boolean reviewedByUser;
	private Boolean reviewedByEmployee;
	private Boolean deleteFlag;

	public Transaction() {
	}

	public Transaction(int transactionId,
			AccountSummary accountSummaryBySender,
			AccountSummary accountSummaryByReceiver, int amount, String time) {
		this.transactionId = transactionId;
		this.accountSummaryBySender = accountSummaryBySender;
		this.accountSummaryByReceiver = accountSummaryByReceiver;
		this.amount = amount;
		this.time = time;
	}

	public Transaction(int transactionId,
			AccountSummary accountSummaryBySender, Employee employee,
			AccountSummary accountSummaryByReceiver, int amount, String time,
			Boolean critical, Boolean reviewedByUser,
			Boolean reviewedByEmployee, Boolean deleteFlag) {
		this.transactionId = transactionId;
		this.accountSummaryBySender = accountSummaryBySender;
		this.employee = employee;
		this.accountSummaryByReceiver = accountSummaryByReceiver;
		this.amount = amount;
		this.time = time;
		this.critical = critical;
		this.reviewedByUser = reviewedByUser;
		this.reviewedByEmployee = reviewedByEmployee;
		this.deleteFlag = deleteFlag;
	}

	@Id
	@Column(name = "TRANSACTION_ID", unique = true, nullable = false)
	public int getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(int transactionId) {
		this.transactionId = transactionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SENDER", nullable = false)
	public AccountSummary getAccountSummaryBySender() {
		return this.accountSummaryBySender;
	}

	public void setAccountSummaryBySender(AccountSummary accountSummaryBySender) {
		this.accountSummaryBySender = accountSummaryBySender;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID_REVIEWING_TRANSACTION")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RECEIVER", nullable = false)
	public AccountSummary getAccountSummaryByReceiver() {
		return this.accountSummaryByReceiver;
	}

	public void setAccountSummaryByReceiver(
			AccountSummary accountSummaryByReceiver) {
		this.accountSummaryByReceiver = accountSummaryByReceiver;
	}

	@Column(name = "AMOUNT", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	@Column(name = "TIME", nullable = false, length = 20)
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	@Column(name = "CRITICAL")
	public Boolean getCritical() {
		return this.critical;
	}

	public void setCritical(Boolean critical) {
		this.critical = critical;
	}

	@Column(name = "REVIEWED_BY_USER")
	public Boolean getReviewedByUser() {
		return this.reviewedByUser;
	}

	public void setReviewedByUser(Boolean reviewedByUser) {
		this.reviewedByUser = reviewedByUser;
	}

	@Column(name = "REVIEWED_BY_EMPLOYEE")
	public Boolean getReviewedByEmployee() {
		return this.reviewedByEmployee;
	}

	public void setReviewedByEmployee(Boolean reviewedByEmployee) {
		this.reviewedByEmployee = reviewedByEmployee;
	}

	@Column(name = "DELETE_FLAG")
	public Boolean getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

}
