package com.db;
// default package
// Generated Nov 6, 2014 12:59:42 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usercritical generated by hbm2java
 */
@Entity
@Table(name = "usercritical", catalog = "cse545group4bank")
public class Usercritical implements java.io.Serializable {

	private String username;
	private String ssn;
	private String employeeIdRequested;
	private Boolean isAdminApproved;
	private String emailId;

	public Usercritical() {
	}

	public Usercritical(String username) {
		this.username = username;
	}

	public Usercritical(String username, String ssn,
			String employeeIdRequested, Boolean isAdminApproved, String emailId) {
		this.username = username;
		this.ssn = ssn;
		this.employeeIdRequested = employeeIdRequested;
		this.isAdminApproved = isAdminApproved;
		this.emailId = emailId;
	}

	@Id
	@Column(name = "USERNAME", unique = true, nullable = false, length = 40)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "SSN", length = 45)
	public String getSsn() {
		return this.ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	@Column(name = "EMPLOYEE_ID_REQUESTED", length = 45)
	public String getEmployeeIdRequested() {
		return this.employeeIdRequested;
	}

	public void setEmployeeIdRequested(String employeeIdRequested) {
		this.employeeIdRequested = employeeIdRequested;
	}

	@Column(name = "IS_ADMIN_APPROVED")
	public Boolean getIsAdminApproved() {
		return this.isAdminApproved;
	}

	public void setIsAdminApproved(Boolean isAdminApproved) {
		this.isAdminApproved = isAdminApproved;
	}

	@Column(name = "EMAIL_ID", length = 45)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

}
